version: '3'
services:
  faktory:
    image: contribsys/faktory:latest
    ports:
      - 7419:7419
      - 7420:7420
    volumes:
      - ./tmp/faktory_data:/var/lib/faktory/db
    command: /faktory -b :7419 -w :7420 -e development
